chatroom/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length


class ChatForm(FlaskForm):
    message = StringField(validators=[DataRequired(), Length(min=0, max=65534, message='Character Count exceeded')])
    submit = SubmitField()

post/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, FileField
from wtforms.validators import Required


class PostForm(FlaskForm):
    title = StringField(validators=[Required()])
    image = FileField()
    body = TextAreaField(validators=[Required()])
    submit = SubmitField()


class CharityPostForm(FlaskForm):
    title = StringField(validators=[Required()])
    location = StringField(validators=[Required()])
    image = FileField()
    body = TextAreaField(validators=[Required()])
    submit = SubmitField()

search/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import DataRequired, Length


class SearchForm(FlaskForm):
    search = StringField(validators=[DataRequired(), Length(min=0, max=65534, message='Character Count exceeded')])
    submit = SubmitField()

chatroom/views.py
from flask import Blueprint, render_template, request
from flask_login import current_user, login_required, LoginManager
from sqlalchemy import desc
from models import Chatroom, User
from chatroom.forms import ChatForm
from app import db

# CONFIG
chatroom_blueprint = Blueprint('chatroom', __name__, template_folder='templates')

# If request method is POST or form valid then add the users chat to database with allocated data.


# VIEWS
@chatroom_blueprint.route('/chatroom', methods=('GET', 'POST'))
# @login_required
def chatroom():

    form = ChatForm()

    chats = Chatroom.query.order_by('post_time').all()

    if form.validate_on_submit():

        # get an unused number to give the 'chat' a unique ID
        next_chat_id = Chatroom.query.order_by(desc('chat_id')).first().chat_id + 1

        new_chat = Chatroom(chat_id=next_chat_id,
                            content=form.message.data,
                            user_id=current_user.user_id)
        # add the chat
        db.session.add(new_chat)
        db.session.commit()
        # reload the page once chatted so that you can see your message.
        chats = Chatroom.query.order_by('post_time').all()
        return render_template('chatroom.html', form=form, chats=chats)

    # load the page the first time
    return render_template('chatroom.html', form=form, chats=chats)

contact/views.py
from flask import Blueprint, render_template, request
from contact.forms import ContactForm
import csv
from pathlib import Path

contact_blueprint = Blueprint('contact', __name__, template_folder='templates')

# Allows user to create a contact form with name email and message, then they're returned to the home page


@contact_blueprint.route('/contact', methods=['GET', 'POST'])
def contact():
    # create contact form object
    form = ContactForm()

    # if request method is POST or form is valid
    if form.validate_on_submit():
        # contact message file store path
        CONTACT_DIR = Path(__file__).resolve().parent.parent.joinpath('contact.csv')
        f = open(CONTACT_DIR, "a", newline='')
        writer = csv.writer(f)
        contact_massage = list()
        contact_massage.append(form.name.data)
        contact_massage.append(form.email.data)
        contact_massage.append(form.message.data)
        writer.writerow(contact_massage)
        f.close()
        return render_template('index.html')
    return render_template('contact_us.html',form=form)
    # Loads contact us page so the user can create a form

post/views.py
import copy
from flask import Blueprint, render_template
from flask_login import login_required, current_user
from sqlalchemy import desc
from app import db
from post.forms import PostForm, CharityPostForm
from models import Post, User, Like

post_blueprint = Blueprint('post', __name__, template_folder='templates')

# Returns a stream of posts ordered by post ID


@post_blueprint.route('/post')
def feed():
    posts = Post.query.order_by(desc('post_id')).all()
    return render_template('home.html', posts=posts)
# renders the home page so the user can view

# Creates a post with allocated post information and increases the next post's post ID by 1


@post_blueprint.route('/create', methods=('GET', 'POST'))
def create():
    form = PostForm()
    if current_user.role == "Charity":
        form = CharityPostForm()

    next_post_id = Post.query.order_by(desc('post_id')).first().post_id + 1

    if form.validate_on_submit():
        new_post = Post(post_id=next_post_id,
                        user_id=current_user.user_id,
                        title=form.title.data,
                        body=form.body.data,
                        post_img=form.image.data)
        if current_user.role == "charity":
            new_post.location = form.location.data

        db.session.add(new_post)
        db.session.commit()

        return feed()
    return render_template('post.html', form=form)
# loads the post template so users can enter post information then submit

# Allows user to update post, if the query returns no post a 500 error is displayed, if the user ID is not equal
# to the post user ID then the option to edit post will not appear, otherwise the user will be able to update
# the title and body of the post and submit it, adding it to the data base


@post_blueprint.route('/<int:post_id>/update', methods=('GET', 'POST'))
def update(post_id):
    post = Post.query.filter_by(post_id=post_id).first()
    if not post:
        return render_template('500.html')

    if post.user_id != current_user.user_id:
        return feed()

    form = PostForm()
    if current_user.role == "charity":
        form = CharityPostForm()

    if form.validate_on_submit():
        post.update_post(form.title.data, form.body.data)
        return feed()

    form.title.data = post.title
    form.body.data = post.body

    return render_template('post.html', form=form)
# Loads post template allowing the user to edit

# If there is no post returned by the query or the user ID is not equal to the post user ID then the delete post
# button will not show, otherwise the user will be able to delete the post, removing it from the databse

@post_blueprint.route('/<int:post_id>/delete')
def delete(post_id):
    post = Post.query.filter_by(post_id=post_id).first()
    if not post or post.user_id != current_user.user_id:
        return feed()

    Post.query.filter_by(post_id=post_id).delete()
    db.session.commit()

    return feed()

# If a post is returned by the query the user will have an option to like the post


@post_blueprint.route('/<int:post_id>/toggle_like')
def toggle_like(post_id):
    liked_post = Post.query.filter_by(post_id=post_id).first()
    liked_post.toggle_like(current_user.user_id)

    return feed()

quiz/views.py
from flask import Blueprint, render_template, request, redirect, url_for
import csv
from pathlib import Path

quiz_blueprint = Blueprint('quiz', __name__, template_folder='templates')

# use for store path of quiz file, quiz score and question No
class quizConfig():
    # quiz file store path
    QUIZ_DIR = Path(__file__).resolve().parent.parent.joinpath('quiz.txt')
    f = csv.reader(open(QUIZ_DIR, "r"))
    questions = list()
    for i in f:
        questions.append(i)

    quiz_score = 0
    question_no = 0


# add new object for new quiz
quiz_config = quizConfig()


# view quiz
@quiz_blueprint.route('/quiz', methods=['GET', 'POST'])
def quiz():
    quiz_btn_txt = "Next"
    return render_template('quiz.html', question=quiz_config.questions[0][0], question_no=quiz_config.question_no + 1,
                           ans1=quiz_config.questions[0][1], ans2=quiz_config.questions[0][2],
                           ans3=quiz_config.questions[0][3], quiz_btn_txt=quiz_btn_txt,
                           link=quiz_config.questions[0][4],
                           score=quiz_config.quiz_score)


# if click new question
@quiz_blueprint.route('/next_question', methods=['GET', 'POST'])
def next_question():
    # if user not give answer for checkbox, refresh page
    if not request.form.get("answer"):
        return render_template('quiz.html',
                               question=quiz_config.questions[quiz_config.question_no][0],
                               question_no=quiz_config.question_no + 1,
                               ans1=quiz_config.questions[quiz_config.question_no][1],
                               ans2=quiz_config.questions[quiz_config.question_no][2],
                               ans3=quiz_config.questions[quiz_config.question_no][3],
                               quiz_btn_txt="Next",
                               link=quiz_config.questions[quiz_config.question_no][4],
                               answer_txt="Please choose one choice!",
                               score=quiz_config.quiz_score)
    # question move to next one
    quiz_config.question_no += 1
    answer_txt = ""
    # check answer is correct or not, then move to next question
    if quiz_config.question_no < 5:
        if request.form["answer"] == "1":
            answer_txt = "Correct answer!"
            quiz_config.quiz_score += 1
        else:
            answer_txt = "Incorrect answer!"
        return render_template('quiz.html',
                               question=quiz_config.questions[quiz_config.question_no][0],
                               question_no=quiz_config.question_no + 1,
                               ans1=quiz_config.questions[quiz_config.question_no][1],
                               ans2=quiz_config.questions[quiz_config.question_no][2],
                               ans3=quiz_config.questions[quiz_config.question_no][3],
                               quiz_btn_txt="Next",
                               link=quiz_config.questions[quiz_config.question_no][4],
                               answer_txt=answer_txt,
                               score=quiz_config.quiz_score)
    # if finish quiz, show score and answer text
    elif quiz_config.question_no == 5:
        temp_score = 0
        if request.form["answer"] == "1":
            temp_score = quiz_config.quiz_score + 1
        quiz_config.quiz_score = 0
        quiz_config.question_no = 0
        answer_txt = "Congratulations on completing the test!"
        return render_template('quiz.html', score=temp_score, answer_txt=answer_txt,
                               quiz_btn_txt="Finish")

search/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_required
from sqlalchemy import desc
from models import User, Post
from search.forms import SearchForm
from app import db

# CONFIG
search_blueprint = Blueprint('search', __name__, template_folder='templates')


# VIEWS
@search_blueprint.route('/search', methods=('GET', 'POST'))
@login_required
def search():

    form = SearchForm()

    if form.validate_on_submit():

        # get the accounts with the searched for username
        user_results = User.query.filter_by(username=form.search.data).all()
        # get the posts with the searched for title
        post_results = Post.query.filter_by(title=form.search.data).all()

        # get the count of each of these, when using count() on user_results it would have an argument error
        user_count = User.query.filter_by(username=form.search.data).count()
        post_count = Post.query.filter_by(title=form.search.data).count()
        # get the total count
        result_count = user_count + post_count
        # do the function to render the template
        return search_result(user_results, post_results, result_count)

    return render_template('search.html', form=form)


@search_blueprint.route('/search_result', methods=('GET', 'POST'))
@login_required
def search_result(user_results, post_results, result_count):
    form = SearchForm()

    return render_template('search_results.html', form=form,
                           user_results=user_results, post_results=post_results, count=result_count)
# Displays the search result template so the user can select their desired result

users/views.py
# IMPORTS
import logging
import pyotp

from datetime import datetime
from flask import Blueprint, render_template, flash, redirect, url_for, request, session
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.security import check_password_hash, generate_password_hash

from app import db, requires_roles
from models import User
from users.forms import RegisterForm, LoginForm

users_blueprint = Blueprint('users', __name__, template_folder='templates')


# view user login
@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():

    session['logins'] = 0
    # if session attribute logins does not exist create attribute logins
    if not session.get('logins'):
        session['logins'] = 0
    # if login attempts is 3 or more create an error message
    elif session.get('logins') >= 3:
        flash('Number of incorrect logins exceeded')

    # create login form object
    form = LoginForm()

    # if request method is POST or form is valid
    if form.validate_on_submit():

        # increase login attempts by 1
        session['logins'] += 1

        user = User.query.filter_by(email=form.username.data).first()
        # login failed
        if not user or not check_password_hash(user.password, form.password.data):

            # if no match create appropriate error message based on login attempts
            if session['logins'] == 3:
                flash('Number of incorrect logins exceeded')
            elif session['logins'] == 2:
                flash('Please check your login details and try again. 1 login attempt remaining')
            else:
                flash('Please check your login details and try again. 2 login attempts remaining')

            # log for invalid login attempts
            logging.warning('SECURITY - Unauthorised login attempt [Anonymous user, %s, %s]', form.username.data,
                            request.remote_addr)

            return render_template('sign_in.html', form=form)

        # verify the PIN submitted by the user
        if pyotp.TOTP(user.pin_key).verify(form.pin_key.data):

            # if user is verified reset login attempts to 0
            session['logins'] = 0

            # register the user as logged in
            login_user(user)

            # last_logged_in is updated to current_logged_in
            user.last_logged_in = user.current_logged_in
            # current_logged_in is updated to current time
            user.current_logged_in = datetime.now()
            # update to database
            db.session.add(user)
            db.session.commit()

            # log for User log in
            logging.warning('SECURITY - Log in [%s, %s, %s]', current_user.user_id, current_user.email,
                            request.remote_addr)

            # direct to role appropriate page
            if current_user.role == 'admin':
                return redirect(url_for('admin.admin'))
            else:
                return redirect(url_for('profiles.profiles', username=user.username))

            # login successful return profile page
            # return profile()

        # 2FA token error, login unsuccessful
        else:
            flash("You have supplied an invalid 2FA token!", "danger")

    return render_template('sign_in.html', form=form)


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    # create signup form object
    form = RegisterForm()


    # if request method is POST or form is valid
    if form.validate_on_submit():
        a = 4
        useremail = User.query.filter_by(email=form.email.data).first()
        username = User.query.filter_by(username=form.username.data).first()
        # if this returns a user, then the email already exists in database

        # if email already exists redirect user back to signup page with error message so user can try again
        if useremail or username:
            flash('Username/Email address already exists')
            return render_template('sign_up.html', form=form)

        # create a new user with the form data
        new_user = User(email=form.email.data,
                        username=form.username.data,
                        firstname=form.firstname.data,
                        lastname=form.lastname.data,
                        password=form.password.data,
                        pin_key=form.pin_key.data,
                        role=form.role.data)

        # add the new user to the database
        db.session.add(new_user)
        db.session.commit()

        # log for User register
        logging.warning('SECURITY - User registration [%s, %s]', form.email.data, request.remote_addr)

        # return user to login page redirect
        return redirect(url_for('index'))

    # if request method is GET or form not valid re-render signup page
    return render_template('sign_up.html', form=form, user_role=get_roles(), otp=pyotp.random_base32())


# get user roles
def get_roles():
    user_role = ["Personal", "Company", "Charity"]
    return user_role

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- cite from: Start Bootstrap https://startbootstrap.com/theme/agency -->
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Gather</title>
        <!-- icon-->
        <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='/img/Gather_logo.png') }}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&family=Oswald:wght@500&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
        <!-- jQuery -->
		<script type="text/javascript" src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{{ url_for('static', filename='/css/styles.css') }}" rel="stylesheet" />
        <link href="{{ url_for('static', filename='/css/styles_nm.css') }}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{{ url_for('index') }}"><img src="{{ url_for('static', filename='/img/Gather.png') }}" alt="Gather" style="width:148.2px;height:68.7px;margin-top: 0;" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                        <!--everyone can access to index page-->
                        <!--<li class="nav-item"><a class="nav-link" href="{{ url_for('index') }}">Information</a></li>-->
                        <!--only authenticated user can access other page-->
                        {% if current_user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{{ url_for('post.feed') }}">Home</a></li>
                            <li class="nav-item"><a class="nav-link" href="{{ url_for('topics') }}">Topics</a></li>
                            <li class="nav-item"><a class="nav-link" href="{{ url_for('post.create') }}">Post</a></li>
                            <li class="nav-item"><a class="nav-link" href="{{ url_for('chatroom.chatroom') }}">Chatroom</a></li>
                            <li class="nav-item"><a class="nav-link" href="{{ url_for('profiles.profiles', username=current_user.username) }}">Profile</a></li>
                            <li class="nav-item"><a class="nav-link" href="{{ url_for('search.search') }}">Search</a></li>
                        {% endif %}
                        <!-- only admin user can access to admin page -->
                        {% if current_user.is_authenticated and current_user.role=='admin'%}
                            <li class="nav-item"><a class="nav-link" href="{{ url_for('admin.admin') }}">Admin</a></li>
                        {% endif %}
                        <!--only unauthenticated user can access sign in and sign up page-->
                        {% if not current_user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{{ url_for('users.login') }}">Sign In</a></li>
                            <li class="nav-item"><a class="nav-link" href="{{ url_for('users.register') }}">Register</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        {% block content %}
        {% endblock %}
        <!-- Footer -->
		  <footer class="bg-white">
			<div class="container py-5">
			  <div class="row py-4">
				<div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
                  <!-- goals for our website -->
				  <p class="font-italic text-muted"><i>Gather's goal is to work towards bringing people,
                      companies, and charities together and reinvigorating global partnerships for sustainable development.</i></p>
				</div>
				<div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
                  <!-- provide services -->
				  <h6 class="text-uppercase font-weight-bold mb-4">Services</h6>
				  <ul class="list-unstyled mb-0">
					<li class="mb-2"><a href="{{ url_for('search.search') }}" class="text-muted">Search</a></li>
					<li class="mb-2"><a href="{{ url_for('contact.contact') }}" class="text-muted">Contact us</a></li>
				  </ul>
				</div>
				<div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
                  <!-- provide quick links -->
				  <h6 class="text-uppercase font-weight-bold mb-4">Quick links</h6>
				  <ul class="list-unstyled mb-0">
					<li class="mb-2"><a href="{{ url_for('quiz.quiz') }}" class="text-muted">Quiz</a></li>
					<li class="mb-2"><a href="{{ url_for('index') }}" class="text-muted">Info</a></li>
				  </ul>
				</div>
				<div class="col-lg-4 col-md-6 mb-lg-0">
                  <!-- Website email  -->
				  <h6 class="text-uppercase font-weight-bold mb-4">NEWSLETTER</h6>
				  <p class="text-muted mb-4">If you have any concerns about our website, please send us an email</p>
				  <div class="p-1 rounded border">
					<div class="input-group">
					  <input type="email" placeholder="gblpartnershipncl@ncl.ac.uk" aria-describedby="button-addon1"
                             class="form-control border-0 shadow-0" disabled="disabled">
					  <div class="input-group-append">
                        <!-- contact us -->
						<button id="button-addon1" type="submit" class="btn btn-link">
                            <a href="{{ url_for('contact.contact') }}"><i class="fa fa-paper-plane"></i></a>
                        </button>
					  </div>
					</div>
				  </div>
				</div>
			  </div>
			</div>

			<!-- Copyrights -->
			<div class="bg-light py-4">
			  <div class="container text-center">
				<p class="text-muted mb-0 py-2">© 2022 Gather Newcastle All rights reserved.</p>
			  </div>
			</div>
		  </footer>
		  <!-- End -->
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css"></script>
        <!-- Core theme JS-->
        <script src="{{ url_for('static', filename='/js/scripts.js') }}" ></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" ></script>
        <!-- import SB Forms JS -->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
    <!-- Post feed page -->
        <section id="feed">
			<section id="feed-container">
                <h2 style="margin-bottom: 20px; margin-left: 40px;">POSTS</h2>
                {% for post in posts %}
				<div class="feed-body">
					<div class="feed-text">
                        <!-- feed heading -->
						<span class="feed-title">{{ post.title }}</span>
                        <!-- user profile -->
						<a href="#"><img class="feed-user-profile" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTN2daTXDiaP8FSM7TKmVmGnQrV0v_gH8YBAq0AvE0PHBzibzftwQkpG7m1a56sc0SvvSE&usqp=CAU" alt="user profile"></a>
						<ul class="feed-user-wrap">
                            <!-- username -->
							<li class="feed-user-inline"><a href="{{ url_for('profiles.profiles', username=post.get_username(post.user_id)) }}">{{ post.get_username(post.user_id) }}</a></li>
                            <!-- date & time -->
							<li class="feed-user-inline">{{ post.post_time }}</li>
                            <li class="feed-user-inline">{{ post.get_likes() }} likes</li>
                            {% if post.location != "0" %}
                            <li class="feed-user-inline">{{ type(post.location) }}</li>
                            {% endif %}
						</ul>
{#                        <!-- post image -->#}
{#						<div class="feed-img-box" href="#">#}
{#						<img src="../static/img/blog-test.jpg" alt="Post Picture">#}
{#						</div>#}
                        <!-- post feed content -->
						<p class="feed-paragraph">{{ post.body }}</p>

						<div class="feed-update-delete">
							{% if current_user.user_id == post.user_id %}
                            	<a class="navbar-item" href="{{ url_for('post.update', post_id=post.post_id) }}">Update</a>
                            	<a class="navbar-item" href="{{ url_for('post.delete', post_id=post.post_id) }}">Delete</a>
                            {% endif %}
							{% if current_user.has_liked(post.post_id) %}
								<a class="navbar-item" href="{{ url_for('post.toggle_like', post_id=post.post_id) }}">Unlike Post</a>
							{% else %}
								<a class="navbar-item" href="{{ url_for('post.toggle_like', post_id=post.post_id) }}">Like Post</a>
							{% endif %}
						</div>
					</div>
				</div>
				{% endfor %}
			</section>
            <!-- popular feed -->
			<section id="feed-popular">
				<div class="feed-popular-container">
					<div class="feed-popular">
                        <!-- heading -->
						<div class="feed-pop-title"><b>Popular Posts</b></div>
						<br />
						<!-- popular post 1 -->
						{% for like in likes %}
						<div class="pop-post">
                            <!-- post image -->
							<a href="#"><img src="../static/img/blog-test.jpg" alt="post img"></a>
                                <!-- post title -->
								<div class="pop-post-wrap">
									<a class="post-title" href="/post/{{ like[0].post_id }}">{{ like[0].title }}</a> </br>
									<span class="post-title">@{{ like[0].get_user().username }} - {{ like[1] }} likes</span>
								<br />
							</div>
						</div>
						{% endfor %}
					</div>
				</div>
            </section>
        </section>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
    <!-- Home page -->
        <!-- video for goal 17 -->
        <section class="main">
            <div class="container">
                <video id="background-video" autoplay loop muted poster="https://assets.codepen.io/6093409/river.jpg">
                    <source src="https://www.data4sdgs.org/themes/gesso/images/videos/video-hero.mp4" type="video/mp4">
                </video>
                <!-- main title -->
                <div class="main-heading text-uppercase">Partnership for the goals.</div>
                <!-- sub title -->
                <div class="main-subheading">Strengthen the means of implementation and revitalize the global partnership for sustainable development.</div>
                <a class="btn btn-primary btn-xl text-uppercase" href="#introduction">More Information</a>
            </div>
        </section>
		<section class="index-introduction" id="introduction">
            <!-- Aphorisms -->
			<div class="index-intro-box intro-box-extend-1">
				<p class="index-intro-content" style="margin-top: 3%;">The Sustainable Development Goals are more important now than ever. Now is the time to secure the well-being of people, economies, societies and our planet. </p>
				<p class="index-intro-name">António Guterres <br />
					Secretary-General, United Nations</p>
				<div class="index-intro-margin"></div>
				<p >Source: <a class="index-intro-source" href="https://unstats.un.org/sdgs/report/2021/">Progress towards the Sustainable Development Goals</a></p>
			</div>
            <!-- Introduction -->
			<div class="index-intro-box intro-box-extend-2">
				<h3 style="margin-top: 0; margin-bottom: 5%;">Introduction</h3>
				<p class="index-intro-content" style="font-size: 1.1rem;">The Global Partnership for Sustainable Development Data is a multi-stakeholder network of more than 300 data champions working to galvanize political commitments, align strategic priorities, foster collaboration, spur innovations, build capacity and enhance trust in the booming data ecosystems of the 21st century.</p>
				<div style="margin: 8%;"></div>
				<p >Source: <a class="index-intro-source" href="https://www.linkedin.com/company/global-partnership-for-sustainable-development-data">Linked in</a></p>
			</div>
            <!-- Quiz -->
			<div class="index-intro-box intro-box-extend-3">
				<div class="index-intro-btn"><a href="{{ url_for('quiz.quiz') }}">START QUIZ !</a></div>
			</div>
		</section>
{% endblock %}